Fix protoc-gen-twirp-es.ts in the protoplugin-example package
bufbuild/protobuf-es pull request #367
Opened 2023-01-19 09:13 UTC by s-hakase

Fix the following bugs in the sample plugin
- The code to output closing brackets was incorrectly positioned, causing unnecessary files to be generated from protos where no RPCs existed.
- Incorrect positioning of code outputting closing brackets was generating incorrect syntax when multiple RPCs existed.
- Unnecessary spaces were being output.

2023-01-19 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bufbuild/protobuf-es?pullRequest=367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bufbuild/protobuf-es?pullRequest=367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bufbuild/protobuf-es?pullRequest=367) it.</sub>

2023-01-19 21:00 UTC, smaye81 requested changes

2023-01-20 02:29 UTC, s-hakase commented on packages/protoplugin-example/src/protoc-gen-twirp-es.ts
> +        f.print("    }");
Thanks for the review.
It was indeed as you said.
I have corrected it, please check again.

2023-01-20 13:56 UTC, smaye81 approved these changes

2023-01-20 13:56 UTC, smaye81 commented
Looks great.  Thanks for the fix @s-hakase!

2023-01-20 13:56 UTC, merged